//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SG50.Model.Models.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Company
    {
        public tbl_Company()
        {
            this.tbl_BusinessUnit = new HashSet<tbl_BusinessUnit>();
            this.tbl_Group = new HashSet<tbl_Group>();
            this.tbl_User = new HashSet<tbl_User>();
            this.tbl_WhiteListIP = new HashSet<tbl_WhiteListIP>();
        }
    
        public System.Guid Id { get; set; }
        public string CompanyName { get; set; }
        public string Email { get; set; }
        public string PhoneNo1 { get; set; }
        public string PhoneNo2 { get; set; }
        public string PhoneNo3 { get; set; }
        public string Fax { get; set; }
        public string Website { get; set; }
        public string Address { get; set; }
        public Nullable<int> PostalCode { get; set; }
        public string City { get; set; }
        public string CountryID { get; set; }
        public string Logo { get; set; }
        public int ShoppingCartHoldingTimeInMinute { get; set; }
        public int MaximumDayForPasswordValidity { get; set; }
        public int MaximumAllowedPasswordFailedAttempt { get; set; }
        public int MaximumAllowedDayBeforeDeleteFile { get; set; }
        public int MaximumAllowedUserInactivityDays { get; set; }
        public int MaximumAllowedDayToApproveFile { get; set; }
        public int MaximumDayForPasswordLifeTime { get; set; }
        public bool IsWhiteListIPCheck { get; set; }
        public byte[] ExecutedTime { get; set; }
        public bool IsActive { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public string UpdatedBy { get; set; }
    
        public virtual ICollection<tbl_BusinessUnit> tbl_BusinessUnit { get; set; }
        public virtual ICollection<tbl_Group> tbl_Group { get; set; }
        public virtual ICollection<tbl_User> tbl_User { get; set; }
        public virtual ICollection<tbl_WhiteListIP> tbl_WhiteListIP { get; set; }
    }
}
