//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SG50.Model.Models.Entities
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class SG50DBEntities : DbContext
    {
        public SG50DBEntities()
            : base("name=SG50DBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<tbl_AppActiveUser> tbl_AppActiveUser { get; set; }
        public virtual DbSet<tbl_AppRole> tbl_AppRole { get; set; }
        public virtual DbSet<tbl_AppUsedPassword> tbl_AppUsedPassword { get; set; }
        public virtual DbSet<tbl_AppUser> tbl_AppUser { get; set; }
        public virtual DbSet<tbl_AppUserClaim> tbl_AppUserClaim { get; set; }
        public virtual DbSet<tbl_AppUserLogin> tbl_AppUserLogin { get; set; }
    }
}
