//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SG50.Model.Models.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_ProgramMenu
    {
        public tbl_ProgramMenu()
        {
            this.tbl_RolePermission = new HashSet<tbl_RolePermission>();
        }
    
        public System.Guid Id { get; set; }
    
        public virtual ICollection<tbl_RolePermission> tbl_RolePermission { get; set; }
    }
}
