//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ngNetCore.Model.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_LoggedInUser
    {
        public System.Guid Id { get; set; }
        public Nullable<System.Guid> UserId { get; set; }
        public string IP { get; set; }
        public string UserAgent { get; set; }
        public string JwtHMACKey { get; set; }
        public Nullable<System.DateTime> IssuedAt { get; set; }
        public Nullable<System.DateTime> ExpiredAt { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<System.Guid> CreatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public Nullable<System.Guid> UpdatedBy { get; set; }
    
        public virtual tbl_User tbl_User { get; set; }
    }
}
