// <auto-generated />
namespace SG50.TokenService.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class initial_table_creation : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(initial_table_creation));
        
        string IMigrationMetadata.Id
        {
            get { return "201510240342372_initial_table_creation"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
