// <auto-generated />
namespace SG50.TokenService.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class ActiveUser_LastRequestedTime : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(ActiveUser_LastRequestedTime));
        
        string IMigrationMetadata.Id
        {
            get { return "201510120649021_ActiveUser_LastRequestedTime"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
