//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GeekQuiz.Model.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class TriviaQuestion
    {
        public TriviaQuestion()
        {
            this.TriviaOptions = new HashSet<TriviaOption>();
        }
    
        public int Id { get; set; }
        public string Title { get; set; }
    
        public virtual ICollection<TriviaOption> TriviaOptions { get; set; }
    }
}
