//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18408
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Consumer_WinForm.RtdbService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="RtdbService.IRtdb", CallbackContract=typeof(Consumer_WinForm.RtdbService.IRtdbCallback), SessionMode=System.ServiceModel.SessionMode.Required)]
    public interface IRtdb {
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IRtdb/ValueChange")]
        void ValueChange(System.Guid SubscriberID, int Value);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IRtdb/ValueChange")]
        System.Threading.Tasks.Task ValueChangeAsync(System.Guid SubscriberID, int Value);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IRtdb/Subscribe")]
        void Subscribe(System.Guid SubscriberID, string TagName);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IRtdb/Subscribe")]
        System.Threading.Tasks.Task SubscribeAsync(System.Guid SubscriberID, string TagName);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IRtdb/UnSubscribe")]
        void UnSubscribe(System.Guid SubscriberID);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IRtdb/UnSubscribe")]
        System.Threading.Tasks.Task UnSubscribeAsync(System.Guid SubscriberID);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IRtdbCallback {
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IRtdb/OnValueChange")]
        void OnValueChange(int Value);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IRtdbChannel : Consumer_WinForm.RtdbService.IRtdb, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class RtdbClient : System.ServiceModel.DuplexClientBase<Consumer_WinForm.RtdbService.IRtdb>, Consumer_WinForm.RtdbService.IRtdb {
        
        public RtdbClient(System.ServiceModel.InstanceContext callbackInstance) : 
                base(callbackInstance) {
        }
        
        public RtdbClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName) : 
                base(callbackInstance, endpointConfigurationName) {
        }
        
        public RtdbClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName, string remoteAddress) : 
                base(callbackInstance, endpointConfigurationName, remoteAddress) {
        }
        
        public RtdbClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(callbackInstance, endpointConfigurationName, remoteAddress) {
        }
        
        public RtdbClient(System.ServiceModel.InstanceContext callbackInstance, System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(callbackInstance, binding, remoteAddress) {
        }
        
        public void ValueChange(System.Guid SubscriberID, int Value) {
            base.Channel.ValueChange(SubscriberID, Value);
        }
        
        public System.Threading.Tasks.Task ValueChangeAsync(System.Guid SubscriberID, int Value) {
            return base.Channel.ValueChangeAsync(SubscriberID, Value);
        }
        
        public void Subscribe(System.Guid SubscriberID, string TagName) {
            base.Channel.Subscribe(SubscriberID, TagName);
        }
        
        public System.Threading.Tasks.Task SubscribeAsync(System.Guid SubscriberID, string TagName) {
            return base.Channel.SubscribeAsync(SubscriberID, TagName);
        }
        
        public void UnSubscribe(System.Guid SubscriberID) {
            base.Channel.UnSubscribe(SubscriberID);
        }
        
        public System.Threading.Tasks.Task UnSubscribeAsync(System.Guid SubscriberID) {
            return base.Channel.UnSubscribeAsync(SubscriberID);
        }
    }
}
